# Generated by Django 3.2.2 on 2021-05-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritesList',
        ),
    ]
