# Generated by Django 3.2.2 on 2021-05-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.CharField(default='1x1x1', max_length=50),
            preserve_default=False,
        ),
    ]
